TARGET= \
  attach.js \
  history.js \
  BaseBorder.css \
  BaseButtons.css \
  BaseStyle.css \
  BaseThin.css \
  print.css \
  natskin.js \
  obfuscator.js

SUBDIRS= \
  ../JazzyNoteTheme

-include Makefile.include
